[tool.poetry]
name = "olauth"
version = "0.1.0"
description = ""
authors = ["OlgaLokhtina <stella_3_@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.135.1"
pydantic = "^2.12.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
